version: '3'

services:
  revproxy:
     container_name: revproxy
     image: nginx:alpine
     restart: always
     ports:
       - 80:80
     volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
     networks:
       - mynet
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3014
    networks:
      - mynet

networks:
    mynet: