version: '3'
services:
  kthb-dialog:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    environment:
      VIRTUAL_HOST: api.sites.lib.kth.se
      LETSENCRYPT_HOST: api.sites.lib.kth.se
      VIRTUAL_PATH: /dialog/
      VIRTUAL_DEST: /dialog/

networks:
  default:
    external:
      name: nginx-proxy